const VERBS_DATA = [
    {
        "infinitive": "hablar",
        "latin": "hablar",
        "ind-pres": ["hablo", "hablas", "hablás", "habla", "hablamos", "habláis", "hablan"],
        "ind-pret": ["hablé", "hablaste", "hablaste", "habló", "hablamos", "hablasteis", "hablaron"],
        "ind-imp": ["hablaba", "hablabas", "hablabas", "hablaba", "hablábamos", "hablabais", "hablaban"],
        "ind-cond": ["hablaría", "hablarías", "hablarías", "hablaría", "hablaríamos", "hablaríais", "hablarían"],
        "ind-fut": ["hablaré", "hablarás", "hablarás", "hablará", "hablaremos", "hablaréis", "hablarán"],
        "subj-pres": ["hable", "hables", "hables", "hable", "hablemos", "habléis", "hablen"],
        "subj-imp1": ["hablara", "hablaras", "hablaras", "hablara", "habláramos", "hablarais", "hablaran"],
        "subj-imp2": ["hablase", "hablases", "hablases", "hablase", "hablásemos", "hablaseis", "hablasen"],
        "subj-fut": ["hablare", "hablares", "hablares", "hablare", "habláremos", "hablareis", "hablaren"],
        "imp-aff": ["habla", "hablá", "hable", "hablemos", "hablad", "hablen"],
        "imp-neg": ["no hables", "no hables", "no hable", "no hablemos", "no habléis", "no hablen"],
        "participle": "hablando",
        "english": ["to talk", "talk", "talks", "talked", "talking"]
    },
    {
    "infinitive": "decir",
    "latin": "decir",
    "ind-pres": ["digo", "dices", "decís", "dice", "decimos", "decís", "dicen"],
    "ind-pret": ["dije", "dijiste", "dijiste", "dijo", "dijimos", "dijisteis", "dijeron"],
    "ind-imp": ["decía", "decías", "decías", "decía", "decíamos", "decíais", "decían"],
    "ind-cond": ["diría", "dirías", "dirías", "diría", "diríamos", "diríais", "dirían"],
    "ind-fut": ["diré", "dirás", "dirás", "dirá", "diremos", "diréis", "dirán"],
    "subj-pres": ["diga", "digas", "digas", "diga", "digamos", "digáis", "digan"],
    "subj-imp1": ["dijera", "dijeras", "dijeras", "dijera", "dijéramos", "dijerais", "dijeran"],
    "subj-imp2": ["dijese", "dijeses", "dijeses", "dijese", "dijésemos", "dijeseis", "dijesen"],
    "subj-fut": ["dijere", "dijeres", "dijeres", "dijere", "dijéremos", "dijereis", "dijeren"],
    "imp-aff": ["di", "decí", "diga", "digamos", "decid", "digan"],
    "imp-neg": ["no digas", "no digas", "no diga", "no digamos", "no digáis", "no digan"],
    "participle": "diciendo",
    "english": ["to say", "say", "says", "said", "saying"],
    "english-alt": ["to tell", "tell", "tells", "told", "telling"]
  },
  {
    "infinitive": "valer",
    "latin": "valer",
    "ind-pres": ["valgo", "vales", "valés", "vale", "valemos", "valéis", "valen"],
    "ind-pret": ["valí", "valiste", "valiste", "valió", "valimos", "valisteis", "valieron"],
    "ind-imp": ["valía", "valías", "valías", "valía", "valíamos", "valíais", "valían"],
    "ind-cond": ["valdría", "valdrías", "valdrías", "valdría", "valdríamos", "valdríais", "valdrían"],
    "ind-fut": ["valdré", "valdrás", "valdrás", "valdrá", "valdremos", "valdréis", "valdrán"],
    "subj-pres": ["valga", "valgas", "valgas", "valga", "valgamos", "valgáis", "valgan"],
    "subj-imp1": ["valiera", "valieras", "valieras", "valiera", "valiéramos", "valierais", "valieran"],
    "subj-imp2": ["valiese", "valieses", "valieses", "valiese", "valiésemos", "valieseis", "valiesen"],
    "subj-fut": ["valiere", "valieres", "valieres", "valiere", "valiéremos", "valiereis", "valieren"],
    "imp-aff": ["vale", "valé", "valga", "valgamos", "valed", "valgan"],
    "imp-neg": ["no valgas", "no valga", "no valga", "no valgamos", "no valgáis", "no valgan"],
    "participle": "valiendo",
    "english": ["to be worth", "am worth", "is worth", "was worth", "being worth"],
    "english-alt": ["to cost", "cost", "costs", "cost", "costing"]
  },
  {
    "infinitive": "comer",
    "latin": "comer",
    "ind-pres": ["como", "comes", "comés", "come", "comemos", "coméis", "comen"],
    "ind-pret": ["comí", "comiste", "comiste", "comió", "comimos", "comisteis", "comieron"],
    "ind-imp": ["comía", "comías", "comías", "comía", "comíamos", "comíais", "comían"],
    "ind-cond": ["comería", "comerías", "comerías", "comería", "comeríamos", "comeríais", "comerían"],
    "ind-fut": ["comeré", "comerás", "comerás", "comerá", "comeremos", "comeréis", "comerán"],
    "subj-pres": ["coma", "comas", "comas", "coma", "comamos", "comáis", "coman"],
    "subj-imp1": ["comiera", "comieras", "comieras", "comiera", "comiéramos", "comierais", "comieran"],
    "subj-imp2": ["comiese", "comieses", "comieses", "comiese", "comiésemos", "comieseis", "comiesen"],
    "subj-fut": ["comiere", "comieres", "comieres", "comiere", "comiéremos", "comiereis", "comieren"],
    "imp-aff": ["come", "comé", "coma", "comamos", "comed", "coman"],
    "imp-neg": ["no comas", "no comas", "no coma", "no comamos", "no comáis", "no coman"],
    "participle": "comiendo",
    "english": ["to eat", "eat", "eats", "ate", "eating"]
  },
  {
    "infinitive": "compartir",
    "latin": "compartir",
    "ind-pres": ["comparto", "compartes", "compartís", "comparte", "compartimos", "compartís", "comparten"],
    "ind-pret": ["compartí", "compartiste", "compartiste", "compartió", "compartimos", "compartisteis", "compartieron"],
    "ind-imp": ["compartía", "compartías", "compartías", "compartía", "compartíamos", "compartíais", "compartían"],
    "ind-cond": ["compartiría", "compartirías", "compartirías", "compartiría", "compartiríamos", "compartiríais", "compartirían"],
    "ind-fut": ["compartiré", "compartirás", "compartirás", "compartirá", "compartiremos", "compartiréis", "compartirán"],
    "subj-pres": ["comparta", "compartas", "compartas", "comparta", "compartamos", "compartáis", "compartan"],
    "subj-imp1": ["compartiera", "compartieras", "compartieras", "compartiera", "compartiéramos", "compartierais", "compartieran"],
    "subj-imp2": ["compartiese", "compartieses", "compartieses", "compartiese", "compartiésemos", "compartieseis", "compartiesen"],
    "subj-fut": ["compartiere", "compartieres", "compartieres", "compartiere", "compartiéremos", "compartiereis", "compartieren"],
    "imp-aff": ["comparte", "compartí", "comparta", "compartamos", "compartid", "compartan"],
    "imp-neg": ["no compartas", "no compartas", "no comparta", "no compartamos", "no compartáis", "no compartan"],
    "participle": "compartiendo",
    "english": ["to share", "share", "shares", "shared", "sharing"]
  },
  {
    "infinitive": "tener",
    "latin": "tĕner",
    "ind-pres": ["tengo", "tienes", "tenés", "tiene", "tenemos", "tenéis", "tienen"],
    "ind-pret": ["tuve", "tuviste", "tuviste", "tuvo", "tuvimos", "tuvisteis", "tuvieron"],
    "ind-imp": ["tenía", "tenías", "tenías", "tenía", "teníamos", "teníais", "tenían"],
    "ind-cond": ["tendría", "tendrías", "tendrías", "tendría", "tendríamos", "tendríais", "tendrían"],
    "ind-fut": ["tendré", "tendrás", "tendrás", "tendrá", "tendremos", "tendréis", "tendrán"],
    "subj-pres": ["tenga", "tengas", "tengas", "tenga", "tengamos", "tengáis", "tengan"],
    "subj-imp1": ["tuviera", "tuvieras", "tuvieras", "tuviera", "tuviéramos", "tuvierais", "tuvieran"],
    "subj-imp2": ["tuviese", "tuvieses", "tuvieses", "tuviese", "tuviésemos", "tuvieseis", "tuviesen"],
    "subj-fut": ["tuviere", "tuvieres", "tuvieres", "tuviere", "tuviéremos", "tuviereis", "tuvieren"],
    "imp-aff": ["ten", "tené", "tenga", "tengamos", "tened", "tengan"],
    "imp-neg": ["no tengas", "no tengas", "no tenga", "no tengamos", "no tengáis", "no tengan"],
    "participle": "teniendo",
    "english": ["to have", "have", "has", "had", "having"]
  },
  {
    "infinitive": "poner",
    "latin": "poner",
    "ind-pres": ["pongo", "pones", "ponés", "pone", "ponemos", "ponéis", "ponen"],
    "ind-pret": ["puse", "pusiste", "pusiste", "puso", "pusimos", "pusisteis", "pusieron"],
    "ind-imp": ["ponía", "ponías", "ponías", "ponía", "poníamos", "poníais", "ponían"],
    "ind-cond": ["pondría", "pondrías", "pondrías", "pondría", "pondríamos", "pondríais", "pondrían"],
    "ind-fut": ["pondré", "pondrás", "pondrás", "pondrá", "pondremos", "pondréis", "pondrán"],
    "subj-pres": ["ponga", "pongas", "pongas", "ponga", "pongamos", "pongáis", "pongan"],
    "subj-imp1": ["pusiera", "pusieras", "pusieras", "pusiera", "pusiéramos", "pusierais", "pusieran"],
    "subj-imp2": ["pusiese", "pusieses", "pusieses", "pusiese", "pusiésemos", "pusieseis", "pusiesen"],
    "subj-fut": ["pusiere", "pusieres", "pusieres", "pusiere", "pusiéremos", "pusiereis", "pusieren"],
    "imp-aff": ["pon", "poné", "ponga", "pongamos", "poned", "pongan"],
    "imp-neg": ["no pongas", "no pongas", "no ponga", "no pongamos", "no pongáis", "no pongan"],
    "participle": "poniendo",
    "english": ["to put", "put", "puts", "put", "putting"],
    "english-alt": ["to place", "place", "places", "placed", "placing"]
  },
  {
    "infinitive": "ser",
    "latin": "ser",
    "ind-pres": ["soy", "eres", "sos", "es", "somos", "sois", "son"],
    "ind-pret": ["fui", "fuiste", "fuiste", "fue", "fuimos", "fuisteis", "fueron"],
    "ind-imp": ["era", "eras", "eras", "era", "éramos", "erais", "eran"],
    "ind-cond": ["sería", "serías", "serías", "sería", "seríamos", "seríais", "serían"],
    "ind-fut": ["seré", "serás", "serás", "será", "seremos", "seréis", "serán"],
    "subj-pres": ["sea", "seas", "seas", "sea", "seamos", "seáis", "sean"],
    "subj-imp1": ["fuera", "fueras", "fueras", "fuera", "fuéramos", "fuerais", "fueran"],
    "subj-imp2": ["fuese", "fueses", "fueses", "fuese", "fuésemos", "fueseis", "fuesen"],
    "subj-fut": ["fuere", "fueres", "fueres", "fuere", "fuéremos", "fuereis", "fueren"],
    "imp-aff": ["sé", "sé", "sea", "seamos", "sed", "sean"],
    "imp-neg": ["no seas", "no seas", "no sea", "no seamos", "no seáis", "no sean"],
    "participle": "siendo",
    "english": ["to be", "am", "is", "was", "being"]
  },
  {
    "infinitive": "estar",
    "latin": "estar",
    "ind-pres": ["estoy", "estás", "estás", "está", "estamos", "estáis", "están"],
    "ind-pret": ["estuve", "estuviste", "estuviste", "estuvo", "estuvimos", "estuvisteis", "estuvieron"],
    "ind-imp": ["estaba", "estabas", "estabas", "estaba", "estábamos", "estabais", "estaban"],
    "ind-cond": ["estaría", "estarías", "estarías", "estaría", "estaríamos", "estaríais", "estarían"],
    "ind-fut": ["estaré", "estarás", "estarás", "estará", "estaremos", "estaréis", "estarán"],
    "subj-pres": ["esté", "estés", "estés", "esté", "estemos", "estéis", "estén"],
    "subj-imp1": ["estuviera", "estuvieras", "estuvieras", "estuviera", "estuviéramos", "estuvierais", "estuvieran"],
    "subj-imp2": ["estuviese", "estuvieses", "estuvieses", "estuviese", "estuviésemos", "estuvieseis", "estuviesen"],
    "subj-fut": ["estuviere", "estuvieres", "estuvieres", "estuviere", "estuviéremos", "estuviereis", "estuvieren"],
    "imp-aff": ["está", "está", "esté", "estemos", "estad", "estén"],
    "imp-neg": ["no estés", "no estés", "no esté", "no estemos", "no estéis", "no estén"],
    "participle": "estando",
    "english": ["to be", "am", "is", "was", "being"],
    "english-alt": ["to be located", "am located", "is located", "was located", "being located"]
  },
  {
    "infinitive": "haber",
    "latin": "haber",
    "ind-pres": ["he", "has", "has", "ha", "hemos", "habéis", "han"],
    "ind-pret": ["hube", "hubiste", "hubiste", "hubo", "hubimos", "hubisteis", "hubieron"],
    "ind-imp": ["había", "habías", "habías", "había", "habíamos", "habíais", "habían"],
    "ind-cond": ["habría", "habrías", "habrías", "habría", "habríamos", "habríais", "habrían"],
    "ind-fut": ["habré", "habrás", "habrás", "habrá", "habremos", "habréis", "habrán"],
    "subj-pres": ["haya", "hayas", "hayas", "haya", "hayamos", "hayáis", "hayan"],
    "subj-imp1": ["hubiera", "hubieras", "hubieras", "hubiera", "hubiéramos", "hubierais", "hubieran"],
    "subj-imp2": ["hubiese", "hubieses", "hubieses", "hubiese", "hubiésemos", "hubieseis", "hubiesen"],
    "subj-fut": ["hubiere", "hubieres", "hubieres", "hubiere", "hubiéremos", "hubiereis", "hubieren"],
    "imp-aff": ["he", "habé", "haya", "hayamos", "habed", "hayan"],
    "imp-neg": ["no hayas", "no hayas", "no haya", "no hayamos", "no hayáis", "no hayan"],
    "participle": "habiendo",
    "english": ["to have", "have", "has", "had", "having"],
    "english-alt": ["there to be", "there is", "there is", "there was", "there being"]
  },
  {
    "infinitive": "ir",
    "latin": "ir",
    "ind-pres": ["voy", "vas", "vas", "va", "vamos", "vais", "van"],
    "ind-pret": ["fui", "fuiste", "fuiste", "fue", "fuimos", "fuisteis", "fueron"],
    "ind-imp": ["iba", "ibas", "ibas", "iba", "íbamos", "ibais", "iban"],
    "ind-cond": ["iría", "irías", "irías", "iría", "iríamos", "iríais", "irían"],
    "ind-fut": ["iré", "irás", "irás", "irá", "iremos", "iréis", "irán"],
    "subj-pres": ["vaya", "vayas", "vayas", "vaya", "vayamos", "vayáis", "vayan"],
    "subj-imp1": ["fuera", "fueras", "fueras", "fuera", "fuéramos", "fuerais", "fueran"],
    "subj-imp2": ["fuese", "fueses", "fueses", "fuese", "fuésemos", "fueseis", "fuesen"],
    "subj-fut": ["fuere", "fueres", "fueres", "fuere", "fuéremos", "fuereis", "fueren"],
    "imp-aff": ["ve", "andá", "vaya", "vayamos", "id", "vayan"],
    "imp-neg": ["no vayas", "no vayas", "no vaya", "no vayamos", "no vayáis", "no vayan"],
    "participle": "yendo",
    "english": ["to go", "go", "goes", "went", "going"]
  },
  {
    "infinitive": "dar",
    "latin": "dar",
    "ind-pres": ["doy", "das", "das", "da", "damos", "dais", "dan"],
    "ind-pret": ["di", "diste", "diste", "dio", "dimos", "disteis", "dieron"],
    "ind-imp": ["daba", "dabas", "dabas", "daba", "dábamos", "dabais", "daban"],
    "ind-cond": ["daría", "darías", "darías", "daría", "daríamos", "daríais", "darían"],
    "ind-fut": ["daré", "darás", "darás", "dará", "daremos", "daréis", "darán"],
    "subj-pres": ["dé", "des", "des", "dé", "demos", "deis", "den"],
    "subj-imp1": ["diera", "dieras", "dieras", "diera", "diéramos", "dierais", "dieran"],
    "subj-imp2": ["diese", "dieses", "dieses", "diese", "diésemos", "dieseis", "diesen"],
    "subj-fut": ["diere", "dieres", "dieres", "diere", "diéremos", "diereis", "dieren"],
    "imp-aff": ["da", "da", "dé", "demos", "dad", "den"],
    "imp-neg": ["no des", "no des", "no dé", "no demos", "no deis", "no den"],
    "participle": "dando",
    "english": ["to give", "give", "gives", "gave", "giving"]
  },
  {
    "infinitive": "ver",
    "latin": "ver",
    "ind-pres": ["veo", "ves", "ves", "ve", "vemos", "veis", "ven"],
    "ind-pret": ["vi", "viste", "viste", "vio", "vimos", "visteis", "vieron"],
    "ind-imp": ["veía", "veías", "veías", "veía", "veíamos", "veíais", "veían"],
    "ind-cond": ["vería", "verías", "verías", "vería", "veríamos", "veríais", "verían"],
    "ind-fut": ["veré", "verás", "verás", "verá", "veremos", "veréis", "verán"],
    "subj-pres": ["vea", "veas", "veas", "vea", "veamos", "veáis", "vean"],
    "subj-imp1": ["viera", "vieras", "vieras", "viera", "viéramos", "vierais", "vieran"],
    "subj-imp2": ["viese", "vieses", "vieses", "viese", "viésemos", "vieseis", "viesen"],
    "subj-fut": ["viere", "vieres", "vieres", "viere", "viéremos", "viereis", "vieren"],
    "imp-aff": ["ve", "ve", "vea", "veamos", "ved", "vean"],
    "imp-neg": ["no veas", "no veas", "no vea", "no veamos", "no veáis", "no vean"],
    "participle": "viendo",
    "english": ["to see", "see", "sees", "saw", "seeing"]
  },
  {
    "infinitive": "oír",
    "latin": "oír",
    "ind-pres": ["oigo", "oyes", "oís", "oye", "oímos", "oís", "oyen"],
    "ind-pret": ["oí", "oíste", "oíste", "oyó", "oímos", "oísteis", "oyeron"],
    "ind-imp": ["oía", "oías", "oías", "oía", "oíamos", "oíais", "oían"],
    "ind-cond": ["oiría", "oirías", "oirías", "oiría", "oiríamos", "oiríais", "oirían"],
    "ind-fut": ["oiré", "oirás", "oirás", "oirá", "oiremos", "oiréis", "oirán"],
    "subj-pres": ["oiga", "oigas", "oigas", "oiga", "oigamos", "oigáis", "oigan"],
    "subj-imp1": ["oyera", "oyeras", "oyeras", "oyera", "oyéramos", "oyerais", "oyeran"],
    "subj-imp2": ["oyese", "oyeses", "oyeses", "oyese", "oyésemos", "oyeseis", "oyesen"],
    "subj-fut": ["oyere", "oyeres", "oyeres", "oyere", "oyéremos", "oyereis", "oyeren"],
    "imp-aff": ["oye", "oí", "oiga", "oigamos", "oíd", "oigan"],
    "imp-neg": ["no oigas", "no oigas", "no oiga", "no oigamos", "no oigáis", "no oigan"],
    "participle": "oyendo",
    "english": ["to hear", "hear", "hears", "heard", "hearing"]
  },
  {
    "infinitive": "caber",
    "latin": "caber",
    "ind-pres": ["quepo", "cabes", "cabés", "cabe", "cabemos", "cabéis", "caben"],
    "ind-pret": ["cupe", "cupiste", "cupiste", "cupo", "cupimos", "cupisteis", "cupieron"],
    "ind-imp": ["cabía", "cabías", "cabías", "cabía", "cabíamos", "cabíais", "cabían"],
    "ind-cond": ["cabría", "cabrías", "cabrías", "cabría", "cabríamos", "cabríais", "cabrían"],
    "ind-fut": ["cabré", "cabrás", "cabrás", "cabrá", "cabremos", "cabréis", "cabrán"],
    "subj-pres": ["quepa", "quepas", "quepas", "quepa", "quepamos", "quepáis", "quepan"],
    "subj-imp1": ["cupiera", "cupieras", "cupieras", "cupiera", "cupiéramos", "cupierais", "cupieran"],
    "subj-imp2": ["cupiese", "cupieses", "cupieses", "cupiese", "cupiésemos", "cupieseis", "cupiesen"],
    "subj-fut": ["cupiere", "cupieres", "cupieres", "cupiere", "cupiéremos", "cupiereis", "cupieren"],
    "imp-aff": ["cabe", "cabé", "quepa", "quepamos", "cabed", "quepan"],
    "imp-neg": ["no quepas", "no quepas", "no quepa", "no quepamos", "no quepáis", "no quepan"],
    "participle": "cabiendo",
    "english": ["to fit", "fit", "fits", "fit", "fitting"]
  },
  {
    "infinitive": "saber",
    "latin": "saber",
    "ind-pres": ["sé", "sabes", "sabés", "sabe", "sabemos", "sabéis", "saben"],
    "ind-pret": ["supe", "supiste", "supiste", "supo", "supimos", "supisteis", "supieron"],
    "ind-imp": ["sabía", "sabías", "sabías", "sabía", "sabíamos", "sabíais", "sabían"],
    "ind-cond": ["sabría", "sabrías", "sabrías", "sabría", "sabríamos", "sabríais", "sabrían"],
    "ind-fut": ["sabré", "sabrás", "sabrás", "sabrá", "sabremos", "sabréis", "sabrán"],
    "subj-pres": ["sepa", "sepas", "sepas", "sepa", "sepamos", "sepáis", "sepan"],
    "subj-imp1": ["supiera", "supieras", "supieras", "supiera", "supiéramos", "supierais", "supieran"],
    "subj-imp2": ["supiese", "supieses", "supieses", "supiese", "supiésemos", "supieseis", "supiesen"],
    "subj-fut": ["supiere", "supieres", "supieres", "supiere", "supiéremos", "supiereis", "supieren"],
    "imp-aff": ["sabe", "sabé", "sepa", "sepamos", "sabed", "sepan"],
    "imp-neg": ["no sepas", "no sepas", "no sepa", "no sepamos", "no sepáis", "no sepan"],
    "participle": "sabiendo",
    "english": ["to know", "know", "knows", "knew", "knowing"],
    "english-alt": ["to know how", "know how", "knows how", "knew how", "knowing how"]
  },
  {
    "infinitive": "empezar",
    "latin": "empĕzar",
    "ind-pres": ["empiezo", "empiezas", "empezás", "empieza", "empezamos", "empezáis", "empiezan"],
    "ind-pret": ["empecé", "empezaste", "empezaste", "empezó", "empezamos", "empezasteis", "empezaron"],
    "ind-imp": ["empezaba", "empezabas", "empezabas", "empezaba", "empezábamos", "empezabais", "empezaban"],
    "ind-cond": ["empezaría", "empezarías", "empezarías", "empezaría", "empezaríamos", "empezaríais", "empezarían"],
    "ind-fut": ["empezaré", "empezarás", "empezarás", "empezará", "empezaremos", "empezaréis", "empezarán"],
    "subj-pres": ["empiece", "empieces", "empieces", "empiece", "empecemos", "empecéis", "empiecen"],
    "subj-imp1": ["empezara", "empezaras", "empezaras", "empezara", "empezáramos", "empezarais", "empezaran"],
    "subj-imp2": ["empezase", "empezases", "empezases", "empezase", "empezásemos", "empezaseis", "empezasen"],
    "subj-fut": ["empezare", "empezares", "empezares", "empezare", "empezáremos", "empezareis", "empezaren"],
    "imp-aff": ["empieza", "empezá", "empiece", "empecemos", "empezad", "empiecen"],
    "imp-neg": ["no empieces", "no empieces", "no empiece", "no empecemos", "no empecéis", "no empiecen"],
    "participle": "empezando",
    "english": ["to begin", "begin", "begins", "begun", "beginning"],
    "english-alt": ["to start", "start", "starts", "started", "starting"]
  },
  {
    "infinitive": "dormir",
    "latin": "dŏrmir",
    "ind-pres": ["duermo", "duermes", "dormís", "duerme", "dormimos", "dormís", "duermen"],
    "ind-pret": ["dormí", "dormiste", "dormiste", "durmió", "dormimos", "dormisteis", "durmieron"],
    "ind-imp": ["dormía", "dormías", "dormías", "dormía", "dormíamos", "dormíais", "dormían"],
    "ind-cond": ["dormiría", "dormirías", "dormirías", "dormiría", "dormiríamos", "dormiríais", "dormirían"],
    "ind-fut": ["dormiré", "dormirás", "dormirás", "dormirá", "dormiremos", "dormiréis", "dormirán"],
    "subj-pres": ["duerma", "duermas", "duermas", "duerma", "durmamos", "durmáis", "duerman"],
    "subj-imp1": ["durmiera", "durmieras", "durmieras", "durmiera", "durmiéramos", "durmierais", "durmieran"],
    "subj-imp2": ["durmiese", "durmieses", "durmieses", "durmiese", "durmiésemos", "durmieseis", "durmiesen"],
    "subj-fut": ["durmiere", "durmieres", "durmieres", "durmiere", "durmiéremos", "durmiereis", "durmieren"],
    "imp-aff": ["duerme", "dormí", "duerma", "durmamos", "dormid", "duerman"],
    "imp-neg": ["no duermas", "no duermas", "no duerma", "no durmamos", "no durmáis", "no duerman"],
    "participle": "durmiendo",
    "english": ["to sleep", "sleep", "sleeps", "slept", "sleeping"]
  },
  {
    "infinitive": "pedir",
    "latin": "pĭdir",
    "ind-pres": ["pido", "pides", "pedís", "pide", "pedimos", "pedís", "piden"],
    "ind-pret": ["pedí", "pediste", "pediste", "pidió", "pedimos", "pedisteis", "pidieron"],
    "ind-imp": ["pedía", "pedías", "pedías", "pedía", "pedíamos", "pedíais", "pedían"],
    "ind-cond": ["pediría", "pedirías", "pedirías", "pediría", "pediríamos", "pediríais", "pedirían"],
    "ind-fut": ["pediré", "pedirás", "pedirás", "pedirá", "pediremos", "pediréis", "pedirán"],
    "subj-pres": ["pida", "pidas", "pidas", "pida", "pidamos", "pidáis", "pidan"],
    "subj-imp1": ["pidiera", "pidieras", "pidieras", "pidiera", "pidiéramos", "pidierais", "pidieran"],
    "subj-imp2": ["pidiese", "pidieses", "pidieses", "pidiese", "pidiésemos", "pidieseis", "pidiesen"],
    "subj-fut": ["pidiere", "pidieres", "pidieres", "pidiere", "pidiéremos", "pidiereis", "pidieren"],
    "imp-aff": ["pide", "pedí", "pida", "pidamos", "pedid", "pidan"],
    "imp-neg": ["no pidas", "no pidas", "no pida", "no pidamos", "no pidáis", "no pidan"],
    "participle": "pidiendo",
    "english": ["to ask for", "ask for", "asks for", "asked for", "asking for"],
    "english-alt": ["to order", "order", "orders", "ordered", "ordering"]
  },
  {
    "infinitive": "perder",
    "latin": "pĕrder",
    "ind-pres": ["pierdo", "pierdes", "perdés", "pierde", "perdemos", "perdéis", "pierden"],
    "ind-pret": ["perdí", "perdiste", "perdiste", "perdió", "perdimos", "perdisteis", "perdieron"],
    "ind-imp": ["perdía", "perdías", "perdías", "perdía", "perdíamos", "perdíais", "perdían"],
    "ind-cond": ["perdería", "perderías", "perderías", "perdería", "perderíamos", "perderíais", "perderían"],
    "ind-fut": ["perderé", "perderás", "perderás", "perderá", "perderemos", "perderéis", "perderán"],
    "subj-pres": ["pierda", "pierdas", "pierdas", "pierda", "perdamos", "perdáis", "pierdan"],
    "subj-imp1": ["perdiera", "perdieras", "perdieras", "perdiera", "perdiéramos", "perdierais", "perdieran"],
    "subj-imp2": ["perdiese", "perdieses", "perdieses", "perdiese", "perdiésemos", "perdieseis", "perdiesen"],
    "subj-fut": ["perdiere", "perdieres", "perdieres", "perdiere", "perdiéremos", "perdiereis", "perdieren"],
    "imp-aff": ["pierde", "perdé", "pierda", "perdamos", "perded", "pierdan"],
    "imp-neg": ["no pierdas", "no pierdas", "no pierda", "no perdamos", "no perdáis", "no pierdan"],
    "participle": "perdiendo",
    "english": ["to lose", "lose", "loses", "lost", "losing"]
  },
  {
    "infinitive": "temer",
    "latin": "temer",
    "ind-pres": ["temo", "temes", "temés", "teme", "tememos", "teméis", "temen"],
    "ind-pret": ["temí", "temiste", "temiste", "temió", "temimos", "temisteis", "temieron"],
    "ind-imp": ["temía", "temías", "temías", "temía", "temíamos", "temíais", "temían"],
    "ind-cond": ["temería", "temerías", "temerías", "temería", "temeríamos", "temeríais", "temerían"],
    "ind-fut": ["temeré", "temerás", "temerás", "temerá", "temeremos", "temeréis", "temerán"],
    "subj-pres": ["tema", "temas", "temas", "tema", "temamos", "temáis", "teman"],
    "subj-imp1": ["temiera", "temieras", "temieras", "temiera", "temiéramos", "temierais", "temieran"],
    "subj-imp2": ["temiese", "temieses", "temieses", "temiese", "temiésemos", "temieseis", "temiesen"],
    "subj-fut": ["temiere", "temieres", "temieres", "temiere", "temiéremos", "temiereis", "temieren"],
    "imp-aff": ["teme", "temé", "tema", "temamos", "temed", "teman"],
    "imp-neg": ["no temas", "no temas", "no tema", "no temamos", "no temáis", "no teman"],
    "participle": "temiendo",
    "english": ["to fear", "fear", "fears", "feared", "fearing"]
  },
  {
    "infinitive": "comenzar",
    "latin": "comĕnzar",
    "ind-pres": ["comienzo", "comienzas", "comenzás", "comienza", "comenzamos", "comenzáis", "comienzan"],
    "ind-pret": ["comencé", "comenzaste", "comenzaste", "comenzó", "comenzamos", "comenzasteis", "comenzaron"],
    "ind-imp": ["comenzaba", "comenzabas", "comenzabas", "comenzaba", "comenzábamos", "comenzabais", "comenzaban"],
    "ind-cond": ["comenzaría", "comenzarías", "comenzarías", "comenzaría", "comenzaríamos", "comenzaríais", "comenzarían"],
    "ind-fut": ["comenzaré", "comenzarás", "comenzarás", "comenzará", "comenzaremos", "comenzaréis", "comenzarán"],
    "subj-pres": ["comience", "comiences", "comiences", "comience", "comencemos", "comencéis", "comiencen"],
    "subj-imp1": ["comenzara", "comenzaras", "comenzaras", "comenzara", "comenzáramos", "comenzarais", "comenzaran"],
    "subj-imp2": ["comenzase", "comenzases", "comenzases", "comenzase", "comenzásemos", "comenzaseis", "comenzasen"],
    "subj-fut": ["comenzare", "comenzares", "comenzares", "comenzare", "comenzáremos", "comenzareis", "comenzaren"],
    "imp-aff": ["comienza", "comenzá", "comience", "comencemos", "comenzad", "comiencen"],
    "imp-neg": ["no comiences", "no comiences", "no comience", "no comencemos", "no comencéis", "no comiencen"],
    "participle": "comenzando",
    "english": ["to begin", "begin", "begins", "begun", "beginning"],
    "english-alt": ["to start", "start", "starts", "started", "starting"]
  },
  {
    "infinitive": "almorzar",
    "latin": "almŏrzar",
    "ind-pres": ["almuerzo", "almuerzas", "almorzás", "almuerza", "almorzamos", "almorzáis", "almuerzan"],
    "ind-pret": ["almorcé", "almorzaste", "almorzaste", "almorzó", "almorzamos", "almorzasteis", "almorzaron"],
    "ind-imp": ["almorzaba", "almorzabas", "almorzabas", "almorzaba", "almorzábamos", "almorzabais", "almorzaban"],
    "ind-cond": ["almorzaría", "almorzarías", "almorzarías", "almorzaría", "almorzaríamos", "almorzaríais", "almorzarían"],
    "ind-fut": ["almorzaré", "almorzarás", "almorzarás", "almorzará", "almorzaremos", "almorzaréis", "almorzarán"],
    "subj-pres": ["almuerce", "almuerces", "almuerces", "almuerce", "almorcemos", "almorcéis", "almuercen"],
    "subj-imp1": ["almorzara", "almorzaras", "almorzaras", "almorzara", "almorzáramos", "almorzarais", "almorzaran"],
    "subj-imp2": ["almorzase", "almorzases", "almorzases", "almorzase", "almorzásemos", "almorzaseis", "almorzasen"],
    "subj-fut": ["almorzare", "almorzares", "almorzares", "almorzare", "almorzáremos", "almorzareis", "almorzaren"],
    "imp-aff": ["almuerza", "almorzá", "almuerce", "almorcemos", "almorzad", "almuercen"],
    "imp-neg": ["no almuerces", "no almuerces", "no almuerce", "no almorcemos", "no almorcéis", "no almuercen"],
    "participle": "almorzando",
    "english": ["to eat lunch", "eat lunch", "eats lunch", "eaten lunch", "eating lunch"],
    "english-alt": ["to have lunch", "have lunch", "has lunch", "had lunch", "having lunch"]
  },
  {
    "infinitive": "desayunar",
    "latin": "desayunar",
    "ind-pres": ["desayuno", "desayunas", "desayunás", "desayuna", "desayunamos", "desayunáis", "desayunan"],
    "ind-pret": ["desayuné", "desayunaste", "desayunaste", "desayunó", "desayunamos", "desayunasteis", "desayunaron"],
    "ind-imp": ["desayunaba", "desayunabas", "desayunabas", "desayunaba", "desayunábamos", "desayunabais", "desayunaban"],
    "ind-cond": ["desayunaría", "desayunarías", "desayunarías", "desayunaría", "desayunaríamos", "desayunaríais", "desayunarían"],
    "ind-fut": ["desayunaré", "desayunarás", "desayunarás", "desayunará", "desayunaremos", "desayunaréis", "desayunarán"],
    "subj-pres": ["desayune", "desayunes", "desayunes", "desayune", "desayunemos", "desayunéis", "desayunen"],
    "subj-imp1": ["desayunara", "desayunaras", "desayunaras", "desayunara", "desayunáramos", "desayunarais", "desayunaran"],
    "subj-imp2": ["desayunase", "desayunases", "desayunases", "desayunase", "desayunásemos", "desayunaseis", "desayunasen"],
    "subj-fut": ["desayunare", "desayunares", "desayunares", "desayunare", "desayunáremos", "desayunareis", "desayunaren"],
    "imp-aff": ["desayuna", "desayuná", "desayune", "desayunemos", "desayunad", "desayunen"],
    "imp-neg": ["no desayunes", "no desayunes", "no desayune", "no desayunemos", "no desayunéis", "no desayunen"],
    "participle": "desayunando",
    "english": ["to eat breakfast", "eat breakfast", "eats breakfast", "eaten breakfast", "eating breakfast"],
    "english-alt": ["to have breakfast", "have breakfast", "has breakfast", "had breakfast", "having breakfast"]
  },
  {
    "infinitive": "lograr",
    "latin": "lograr",
    "ind-pres": ["logro", "logras", "lográs", "logra", "logramos", "lográis", "logran"],
    "ind-pret": ["logré", "lograste", "lograste", "logró", "logramos", "lograsteis", "lograron"],
    "ind-imp": ["lograba", "lograbas", "lograbas", "lograba", "lográbamos", "lograbais", "lograban"],
    "ind-cond": ["lograría", "lograrías", "lograrías", "lograría", "lograríamos", "lograríais", "lograrían"],
    "ind-fut": ["lograré", "lograrás", "lograrás", "logrará", "lograremos", "lograréis", "lograrán"],
    "subj-pres": ["logre", "logres", "logres", "logre", "logremos", "logréis", "logren"],
    "subj-imp1": ["lograra", "lograras", "lograras", "lograra", "lográramos", "lograrais", "lograran"],
    "subj-imp2": ["lograse", "lograses", "lograses", "lograse", "lográsemos", "lograseis", "lograsen"],
    "subj-fut": ["lograre", "lograres", "lograres", "lograre", "lográremos", "lograreis", "lograren"],
    "imp-aff": ["logra", "lográ", "logre", "logremos", "lograd", "logren"],
    "imp-neg": ["no logres", "no logres", "no logre", "no logremos", "no logréis", "no logren"],
    "participle": "logrando",
    "english": ["to achieve", "achieve", "achieves", "achieved", "achieving"],
    "english-alt": ["to manage", "manage", "manages", "managed", "managing"]
  },
  {
    "infinitive": "alimentar",
    "latin": "alimentar",
    "ind-pres": ["alimento", "alimentas", "alimentás", "alimenta", "alimentamos", "alimentáis", "alimentan"],
    "ind-pret": ["alimenté", "alimentaste", "alimentaste", "alimentó", "alimentamos", "alimentasteis", "alimentaron"],
    "ind-imp": ["alimentaba", "alimentabas", "alimentabas", "alimentaba", "alimentábamos", "alimentabais", "alimentaban"],
    "ind-cond": ["alimentaría", "alimentarías", "alimentarías", "alimentaría", "alimentaríamos", "alimentaríais", "alimentarían"],
    "ind-fut": ["alimentaré", "alimentarás", "alimentarás", "alimentará", "alimentaremos", "alimentaréis", "alimentarán"],
    "subj-pres": ["alimente", "alimentes", "alimentes", "alimente", "alimentemos", "alimentéis", "alimenten"],
    "subj-imp1": ["alimentara", "alimentaras", "alimentaras", "alimentara", "alimentáramos", "alimentarais", "alimentaran"],
    "subj-imp2": ["alimentase", "alimentases", "alimentases", "alimentase", "alimentásemos", "alimentaseis", "alimentasen"],
    "subj-fut": ["alimentare", "alimentares", "alimentares", "alimentare", "alimentáremos", "alimentareis", "alimentaren"],
    "imp-aff": ["alimenta", "alimentá", "alimente", "alimentemos", "alimentad", "alimenten"],
    "imp-neg": ["no alimentes", "no alimentes", "no alimente", "no alimentemos", "no alimentéis", "no alimenten"],
    "participle": "alimentando",
    "english": ["to feed", "feed", "feeds", "fed", "feeding"]
  }
];

// Verb format reference:
// {
//   "infinitive": "...",          — display form
//   "latin": "...",               — root/latin form (same as infinitive for regular verbs)
//   "lessons": ["4a", "4b"],      — optional; if present, verb only appears in listed practices
//   "ind-pres": [yo, tú, vos, él, nosotros, vosotros, ellos],
//   ...
// }
//
// yo-go verbs: ind-pres[0] ends in "go" (e.g. "tengo", "pongo", "digo")
